name: wallpaper_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.1+10

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  path_provider: ^2.0.5
  permission_handler: ^8.2.2
  intl: ^0.17.0
  flutter_downloader: ^1.7.0
  cloud_firestore: ^2.5.3
  font_awesome_flutter: ^9.1.0
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  sliding_up_panel: ^2.0.0+1
  flutter_staggered_grid_view: ^0.4.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  google_sign_in: ^5.1.1
  firebase_auth: ^3.1.2
  connectivity: ^3.0.6
  cached_network_image: ^3.1.0
  launch_review: ^3.0.1
  awesome_dialog: ^2.1.1
  shimmer: ^2.0.0
  wallpaper: ^1.0.7
  firebase_core: ^1.7.0
  rounded_loading_button: ^2.0.9
  google_mobile_ads: ^0.13.5
  # facebook_audience_network: ^1.0.0-nullsafety.0
  #ext_storage: ^1.0.3
  ext_storage:
    git:
      url: git://github.com/lavahasif/ext_storage_ups.git
  #onesignal_flutter: ^3.2.7
  onesignal_flutter: #^3.2.3
    git:
      url: https://github.com/luis901101/OneSignal-Flutter-SDK.git
      ref: migrate_android_embedding_v2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.2.4


  
flutter_icons:
  android: "launcher_icon" 
  ios: false
  image_path: "assets/images/icon.png"


flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    
    - assets/images/
 
  fonts:



    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
